BIN := decafs_espresso
OBJS := espresso_core.o

DECAFS_LIBS := espresso_storage/libespresso_storage.a \
               network_core/libnetcore.a \
               net_tcp/libnettcp.a

include ../../app.mk
