LIB = libnetcore.a
OBJS = barista_network_helper.o \
       barista_server.o \
       decafs_client.o \
       espresso_client.o \
       espresso_packet_processor.o \
       network_packets.o \
       open_packet.o \
       open_packet_response.o \
       read_packet.o \
       read_response_packet.o \
       write_response_packet.o \
       close_packet.o \
       close_response_packet.o \
       delete_file_packet.o

include ../../lib.mk
