LIB = libnetcore.a
OBJS = barista_network_helper.o \
       barista_server.o \
       decafs_client.o \
       espresso_client.o \
       espresso_packet_processor.o \
       network_packets.o \
       open_packet.o \
       open_packet_response.o \
       read_packet.o \
       read_response_packet.o \
       write_response_packet.o \
       write_packet.o \
       close_packet.o \
       close_response_packet.o \
       lseek_packet.o \
       lseek_response_packet.o \
       opendir_packet.o \
       opendir_response_packet.o \
       file_storage_stat_packet.o \
       file_storage_stat_response_packet.o \
       mkdir_packet.o \
       mkdir_response_packet.o \
       remove_packet.o \
       remove_response_packet.o
       #delete_file_packet.o \

include ../../lib.mk
