/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NETWORK_H_RPCGEN
#define _NETWORK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct read_params {
	int fd;
	int file_id;
	int stripe_id;
	int chunk_num;
	int offset;
	int count;
};
typedef struct read_params read_params;

struct write_params {
	int fd;
	int file_id;
	int stripe_id;
	int chunk_num;
	int offset;
	char *buf;
	int count;
};
typedef struct write_params write_params;

struct delete_params {
	int file_id;
	int stripe_id;
	int chunk_num;
};
typedef struct delete_params delete_params;

struct read_rtn {
	char *buf;
	int length;
};
typedef struct read_rtn read_rtn;

#define DECAFS_NETWORK_CORE 0x2fffffff
#define DECAFS_NETWORK_CORE_V1 1

// manually added line to change server main
// to a loop that can be called so this can
// be compiled as a library
extern int svc_main_loop(int argc, char** argv); 

#if defined(__STDC__) || defined(__cplusplus)
#define RPC_READ_DATA 1
extern  read_rtn * rpc_read_data_1(read_params *, CLIENT *);
extern  read_rtn * rpc_read_data_1_svc(read_params *, struct svc_req *);
#define RPC_WRITE_DATA 2
extern  int * rpc_write_data_1(write_params *, CLIENT *);
extern  int * rpc_write_data_1_svc(write_params *, struct svc_req *);
#define RPC_DELETE_DATA 3
extern  int * rpc_delete_data_1(delete_params *, CLIENT *);
extern  int * rpc_delete_data_1_svc(delete_params *, struct svc_req *);
extern int decafs_network_core_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC_READ_DATA 1
extern  read_rtn * rpc_read_data_1();
extern  read_rtn * rpc_read_data_1_svc();
#define RPC_WRITE_DATA 2
extern  int * rpc_write_data_1();
extern  int * rpc_write_data_1_svc();
#define RPC_DELETE_DATA 3
extern  int * rpc_delete_data_1();
extern  int * rpc_delete_data_1_svc();
extern int decafs_network_core_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_read_params (XDR *, read_params*);
extern  bool_t xdr_write_params (XDR *, write_params*);
extern  bool_t xdr_delete_params (XDR *, delete_params*);
extern  bool_t xdr_read_rtn (XDR *, read_rtn*);

#else /* K&R C */
extern bool_t xdr_read_params ();
extern bool_t xdr_write_params ();
extern bool_t xdr_delete_params ();
extern bool_t xdr_read_rtn ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NETWORK_H_RPCGEN */
