/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "network.h"

bool_t
xdr_read_params (XDR *xdrs, read_params *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->count))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->fd);
			IXDR_PUT_LONG(buf, objp->file_id);
			IXDR_PUT_LONG(buf, objp->stripe_id);
			IXDR_PUT_LONG(buf, objp->chunk_num);
			IXDR_PUT_LONG(buf, objp->offset);
			IXDR_PUT_LONG(buf, objp->count);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->count))
				 return FALSE;
		} else {
			objp->fd = IXDR_GET_LONG(buf);
			objp->file_id = IXDR_GET_LONG(buf);
			objp->stripe_id = IXDR_GET_LONG(buf);
			objp->chunk_num = IXDR_GET_LONG(buf);
			objp->offset = IXDR_GET_LONG(buf);
			objp->count = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->file_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->stripe_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->chunk_num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_params (XDR *xdrs, write_params *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->fd);
		IXDR_PUT_LONG(buf, objp->file_id);
		IXDR_PUT_LONG(buf, objp->stripe_id);
		IXDR_PUT_LONG(buf, objp->chunk_num);
		IXDR_PUT_LONG(buf, objp->offset);
		}
		 if (!xdr_string (xdrs, &objp->buf, ~0))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;

		} else {
		objp->fd = IXDR_GET_LONG(buf);
		objp->file_id = IXDR_GET_LONG(buf);
		objp->stripe_id = IXDR_GET_LONG(buf);
		objp->chunk_num = IXDR_GET_LONG(buf);
		objp->offset = IXDR_GET_LONG(buf);
		}
		 if (!xdr_string (xdrs, &objp->buf, ~0))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->file_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->stripe_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->chunk_num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->buf, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delete_params (XDR *xdrs, delete_params *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->fd);
			IXDR_PUT_LONG(buf, objp->file_id);
			IXDR_PUT_LONG(buf, objp->stripe_id);
			IXDR_PUT_LONG(buf, objp->chunk_num);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->file_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->stripe_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->chunk_num))
				 return FALSE;
		} else {
			objp->fd = IXDR_GET_LONG(buf);
			objp->file_id = IXDR_GET_LONG(buf);
			objp->stripe_id = IXDR_GET_LONG(buf);
			objp->chunk_num = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->file_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->stripe_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->chunk_num))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_rtn (XDR *xdrs, read_rtn *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->buf, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}
