/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "network.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
decafs_network_core_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		read_params rpc_read_data_1_arg;
		write_params rpc_write_data_1_arg;
		delete_params rpc_delete_data_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RPC_READ_DATA:
		_xdr_argument = (xdrproc_t) xdr_read_params;
		_xdr_result = (xdrproc_t) xdr_read_rtn;
		local = (char *(*)(char *, struct svc_req *)) rpc_read_data_1_svc;
		break;

	case RPC_WRITE_DATA:
		_xdr_argument = (xdrproc_t) xdr_write_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_write_data_1_svc;
		break;

	case RPC_DELETE_DATA:
		_xdr_argument = (xdrproc_t) xdr_delete_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_delete_data_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DECAFS_NETWORK_CORE, DECAFS_NETWORK_CORE_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DECAFS_NETWORK_CORE, DECAFS_NETWORK_CORE_V1, decafs_network_core_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DECAFS_NETWORK_CORE, DECAFS_NETWORK_CORE_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DECAFS_NETWORK_CORE, DECAFS_NETWORK_CORE_V1, decafs_network_core_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DECAFS_NETWORK_CORE, DECAFS_NETWORK_CORE_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
